### ISSUE TITLE
local variable 'val' referenced before assignment

### ISSUE THREAD

**Issue by Sorunome** [eguven/python3-memcached#16]
> memcached = memcache.Client(['127.0.0.1:11211'],debug=0)

> memcached.get('oirc_lines_0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/memcache.py", line 888, in get
    return self._get('get', key)
  File "/usr/lib/python3.5/site-packages/memcache.py", line 872, in _get
    return _unsafe_get()
  File "/usr/lib/python3.5/site-packages/memcache.py", line 861, in _unsafe_get
    value = self._recv_value(server, flags, rlen)
  File "/usr/lib/python3.5/site-packages/memcache.py", line 1026, in _recv_value
    return val
UnboundLocalError: local variable 'val' referenced before assignment

This value was set by another program, the memcached library of PHP and *should* contain a string, if all is working as it should.

**Comment by eguven** [comment]
original repo has added py23 support thus this is deprecated
