### ISSUE TITLE
setup.py not compatible with Python2

### ISSUE THREAD

**Issue by guettli** [eguven/python3-memcached#17]
We run our own pypi server with Python2.

To download packages to this server we use this command:

```
pip download  -d packages python3-memcached
```

Unfortunately this fails, since `setup.py` gets executed by  a Python2 interpreter:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pypi/tmp/pip-build-PfHuTb/python3-memcached/setup.py", line 4, in <module>
        import memcache
      File "memcache.py", line 1251
        print("Testing set/get {'%s': %s} ..." % (to_s(key), to_s(val)), end=' ')
                                                                            ^
    SyntaxError: invalid syntax
```

**Comment by eguven** [comment]
See README, this repo has been deprecated for quite a while
